In [ ]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException
from selenium.webdriver.common.by import By

#Importing requests
import requests

# importing regex
import re

Q1.Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Opening the wikipBy.XPATH,edia
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

time.sleep(2)
#scraping names of the video
name=[]
try:
    names=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    name.append('No details available')

time.sleep(2)
#scraping rank of the video
rank=[]
try:
    ranks=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    rank.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    rank.append('No details available')

time.sleep(2)
#scraping artist/uploader of the video
artist=[]
try:
    artists=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    artist.append('No details available')

time.sleep(2)
#scraping views of the video
views=[]
try:
    views_list=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException:#handling no such element exception
    views.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    views.append('No details available')

time.sleep(2)
#scraping views of the video
upload_date=[]
try:
    upload_date_list=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)

except NoSuchElementException:#handling no such element exception
    upload_date.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    upload_date.append('No details available')

time.sleep(2)
#preparing dataframe
df=pd.DataFrame({"Rank":rank,
                 "Name":name,
                "Uploader/artist":artist,
                "Date of upload":upload_date,
                "Views(in billion)":views})
df

C:\Users\HP\AppData\Local\Temp\ipykernel_11740\2175692238.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

,Rank,Name,Uploader/artist,Date of upload,Views(in billion)
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.13
1,2.,"""Despacito""[7]",Luis Fonsi,"January 12, 2017",8.07
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,"October 8, 2016",6.59
3,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.96
4,5.,"""Shape of You""[16]",Ed Sheeran,"January 30, 2017",5.89
5,6.,"""See You Again""[18]",Wiz Khalifa,"April 6, 2015",5.76
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",5.12
7,8.,"""Wheels on the Bus""[24]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.84
8,9.,"""Uptown Funk""[25]",Mark Ronson,"November 19, 2014",4.80
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,"February 27, 2018",4.79
10,11.,"""Gangnam Style""[27]",Psy,"July 15, 2012",4.66
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.52
12,13.,"""Dame Tu Cosita""[33]",El Chombo,"April 5, 2018",4.21
13,14.,"""Sugar""[34]",Maroon 5,"January 14, 2015",3.81
14,15.,"""Roar""[35]",Katy Perry,"September 5, 2013",3.72
15,16.,"""Counting Stars""[36]",OneRepublic,"May 31, 2013",3.71
16,17.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.71
17,18.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.62
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,"October 7, 2014",3.54
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.48
20,21.,"""Waka Waka (This Time for Africa)""[41]",Shakira,"June 4, 2010",3.44
21,22.,"""Dark Horse""[42]",Katy Perry,"February 20, 2014",3.43
22,23.,"""Faded""[43]",Alan Walker,"December 3, 2015",3.39
23,24.,"""Let Her Go""[44]",Passenger,"July 25, 2012",3.37
24,25.,"""Girls Like You""[45]",Maroon 5,"May 31, 2018",3.36
25,26.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.35
26,27.,"""Bailando""[47]",Enrique Iglesias,"April 11, 2014",3.32
27,28.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.32
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.29
29,30.,"""Lakdi Ki Kathi""[50]",Jingle Toons,"June 14, 2018",3.26

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe")


time.sleep(2)

# Opening the bcci.tv
url = "https://www.bcci.tv/"
driver.get(url)

time.sleep(2)

fixture_tag = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a').click()


time.sleep(2)

C:\Users\HP\AppData\Local\Temp\ipykernel_19064\2485407363.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [ ]:
# creating empty lists
match=[]
series=[]
place=[]
date=[]
Time=[]

#Scrapping Name-
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]'):
        match.append(i.text.replace('-',""))
except NoSuchElementException:
    match.append('-')

#Scrapping Series-
try:

    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
        series.append(i.text)
except NoSuchElementException:
    series.append('-')

#scrapping Place-
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]'):
        place.append(i.text)
except NoSuchElementException:
    place.append('-')

#Scrapping Date-
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]'):
        date.append(i.text)

except NoSuchElementException:
    date.append('-')

#Scrapping Time-
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]'):
        Time.append(i.text.replace('IST',""))

except NoSuchElementException:
    Time.append('-')

In [ ]:
df=pd.DataFrame({'match':match,'series':series,'place':place,'date':date[0:8],'Time':Time[0:8]})
df

,match,series,place,date,Time
0,1st T20I,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park,",19 JAN 2023,10:30 PM
1,2nd ODI,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,Shaheed Veer Narayan Singh International Crick...,21 JAN 2023,1:30 PM
2,2nd T20I,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park,",23 JAN 2023,10:30 PM
3,3rd ODI,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,"Holkar Cricket Stadium,",24 JAN 2023,1:30 PM
4,1st T20I,NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23,"JSCA International Stadium Complex,",27 JAN 2023,7:00 PM
5,3rd T20I,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park,",28 JAN 2023,10:30 PM
6,2nd T20I,NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29 JAN 2023,7:00 PM
7,4th T20I,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park,",30 JAN 2023,6:30 PM

*Q3. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(19-20)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Opening the statisticstimes.com
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

# Clicking on India under ecomony section
India=driver.find_element(By.XPATH,'//div[@class="dropdown"][2]/div/a[3]')
try:
    India.click()
except ElementNotInteractableException:
    driver.get(India.get_attribute('href'))

time.sleep(2)

# Clicking Indian State GDP
state = driver.find_element(By.XPATH,'//ul[@style="list-style-type:none;margin-left:20px;"]/li[1]/a')
try:
    state.click()
except ElementNotInteractableException:
    driver.get(state.get_attribute('href'))
time.sleep(2)

C:\Users\HP\AppData\Local\Temp\ipykernel_26000\1981929090.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [ ]:
Rank=[]
State=[]
GDSP_19_20=[]
GDSP_18_19=[]
Share=[]
GDP=[]

# Extracting Rank via Xpath
try:
    rank=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('NA')

# Extracting state name via Xpath
try:
    state=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
    for i in state:
        State.append(i.text)
except NoSuchElementException:
    State.append('NA')

# Extracting GDSP 19-20 via Xpath
try:
    gdsp_19_20=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gdsp_19_20:
        GDSP_19_20.append(i.text)
except NoSuchElementException:
    GDSP_19_20.append('NA')

# Extracting GDSP 18-19 via Xpath
try:
    gdsp_18_19=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gdsp_18_19:
        GDSP_18_19.append(i.text)
except NoSuchElementException:
    GDSP_18_19.append('NA')

# Extracting share in billons via Xpath
try:
    share=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
    for i in share:
        Share.append(i.text)
except NoSuchElementException:
    Share.append('NA')

# Extracting GDP via Xpath
try:
    gdp=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdp:
        GDP.append(i.text)
except NoSuchElementException:
    GDP.append('NA')

In [ ]:
# Dataframe for scrap data
df=pd.DataFrame({'Rank':Rank,'State':State,'GDSP 19-20':GDSP_19_20,'GDSP 18-19':GDSP_18_19,
                            'Share':Share,'GDP (in Billions)':GDP})
df

,Rank,State,GDSP 19-20,GDSP 18-19,Share,GDP (in Billions)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

* Q4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Opening the github
url = "https://github.com/"
driver.get(url)

C:\Users\HP\AppData\Local\Temp\ipykernel_11552\2925612640.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [ ]:
#Getting explore button and clicking on it
explore = driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[1]/div[2]/button").click()

In [ ]:
#Selecting open source option
open_source = driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
open_source.click()


#Selecting trending option
trending = driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a")
trending.click()

In [ ]:
#Creating empty list
repo_urls = []
rep_title = []
Description = []
Contributors = []
Language = []

In [ ]:
#Scraping urls for each repository
repository = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']//a")
for i in repository[0:30]:
    repo_urls.append(i.get_attribute("href"))


#Scraping data from every repository page
for i in repo_urls:
    driver.get(i)
    time.sleep(3)

    #Scraping description-
    try:
        title = driver.find_element(By.XPATH,'//div[@class=" d-flex flex-wrap flex-items-center wb-break-word f3 text-normal"]')
        rep_title.append(title.text)
    except NoSuchElementException:
        rep_title.append('-')

    #Scraping description-
    try:
        desc = driver.find_element(By.XPATH,'//p[@class="f4 my-3"]')
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')


    #Scraping contributors count-
    try:
        cont_tags = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(cont_tags.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')


    #Scraping Languages-
    try:
        cont_tags = driver.find_element(By.XPATH,'//span[@class="color-fg-default text-bold mr-1"]')
        Language.append(cont_tags.text)
    except NoSuchElementException:
        Language.append('-')

In [ ]:
# Creating Dataframe-
df=pd.DataFrame({'rep_title':rep_title,'Description':Description,'Contributors':Contributors,'Language':Language})
df

,rep_title,Description,Contributors,Language
0,AzeemIdrisi\n/\nPhoneSploit-Pro\nPublic,An all-in-one hacking tool to remotely exploit...,-,Python
1,flutter\n/\nnews_toolkit\nPublic,"A news template application built in Flutter, ...",17,Dart
2,bregman-arie\n/\ndevops-exercises\nPublic,"Linux, Jenkins, AWS, SRE, Prometheus, Docker, ...",129,Python
3,localsend\n/\nlocalsend\nPublic,An open source cross-platform alternative to A...,4,Dart
4,papers-we-love\n/\npapers-we-love\nPublic,Papers from the computer science community to ...,241,Shell
5,jlevy\n/\nthe-art-of-command-line\nPublic,"Master the command line, in one page",164,-
6,geohot\n/\ntinygrad\nPublic,You like pytorch? You like micrograd? You love...,75,Python
7,flutter\n/\nflutter\nPublic,Flutter makes it easy and fast to build beauti...,"1,133",Dart
8,komeilmehranfar\n/\ncompanies-with-remote-posi...,List of companies with remote positions which ...,5,-
9,karpathy\n/\nnn-zero-to-hero\nPublic,Neural Networks: Zero to Hero,2,Jupyter Notebook
10,TheAppleTucker\n/\nbackend-GPT\nPublic,-,3,JavaScript
11,abhivaikar\n/\nhowtheytest\nPublic,A collection of public resources about how sof...,25,HTML
12,TrinityCore\n/\nTrinityCore\nPublic,TrinityCore Open Source MMO Framework (master ...,520,C++
13,LAION-AI\n/\nOpen-Assistant\nPublic,OpenAssistant is a chat-based assistant that u...,96,Python
14,github\n/\ndocs\nPublic,The open-source repo for docs.github.com,"1,683",JavaScript
15,dair-ai\n/\nML-Papers-Explained\nPublic,Explanation to key concepts in ML,3,-
16,excalidraw\n/\nexcalidraw\nPublic,Virtual whiteboard for sketching hand-drawn li...,214,TypeScript
17,airbytehq\n/\nairbyte\nPublic,Data integration platform for ELT pipelines fr...,651,Java
18,PaulWaltersDev\n/\nFreeLearningResourcesForSof...,A New Project to create a set of links to free...,8,-
19,shadcn\n/\nui\nPublic,Beautifully designed components built with Rad...,7,TypeScript
20,ranaroussi\n/\nyfinance\nPublic,Download market data from Yahoo! Finance's API,68,Python
21,mouredev\n/\nhello-git\nPublic,Curso para aprender a trabajar con el sistema ...,17,-
22,withastro\n/\nastro\nPublic,Build faster websites with Astro's next-gen is...,437,TypeScript
23,charliermarsh\n/\nruff\nPublic,"An extremely fast Python linter, written in Rust.",100,Rust
24,donnemartin\n/\nsystem-design-primer\nPublic,Learn how to design large-scale systems. Prep ...,117,Python

Q5. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [ ]:
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)


#Getting url for top 100 -
urls = driver.find_element(By.XPATH,"/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a")
page_url = urls.get_attribute("href")
driver.get(page_url)
time.sleep(4)

#Creating empty list
name = []
artist = []
Last_week_rank = []
peak_rank = []
Weeks = []


#Now we have to extract required info from page url
#Scraping data of song names
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//h3'):
    name.append(i.text)


#Scraping data of artist names
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[1]/span'):
    artist.append(i.text)



#Scraping last week ranks
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[4]/span[1]'):
    Last_week_rank.append(i.text)


#Scraping peak rank
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[5]/span[1]'):
    peak_rank.append(i.text)


#Scraping  weeks on board
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[6]/span[1]'):
    Weeks.append(i.text)

C:\Users\HP\AppData\Local\Temp\ipykernel_12988\4198288638.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

In [ ]:
#creating dataframe
df=pd.DataFrame({"name":name, "artist":artist, 'Last_week_rank':Last_week_rank,'peak_rank':peak_rank,'Weeks':Weeks})
df

,name,artist,Last_week_rank,peak_rank,Weeks
0,Anti-Hero,Taylor Swift,1,1,12
1,Kill Bill,SZA,3,2,5
2,Unholy,Sam Smith & Kim Petras,2,1,16
3,I'm Good (Blue),David Guetta & Bebe Rexha,4,4,20
4,Creepin',"Metro Boomin, The Weeknd & 21 Savage",6,5,6
...,...,...,...,...,...
95,Ditto,NewJeans,-,96,1
96,That's What Tequila Does,Jason Aldean,-,97,1
97,Gone Girl,SZA,94,43,5
98,SOS,SZA,90,32,5
99,You Didn't,Brett Young,-,100,1

* Q6. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

#scrapping book names
book_name=[]
try:
    names=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

#scrapping author names
author_name=[]
try:
    names=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)


#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)

#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

#scrapping genre
genre=[]
try:
    genres=driver.find_elements(By.XPATH,"//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Book_name":book_name, "Author_name":author_name, 'Volume sold':Sale,'Publisher':publisher,'Genre':genre})
df

C:\Users\HP\AppData\Local\Temp\ipykernel_12988\469282098.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")
C:\Users\HP\AppData\Local\Temp\ipykernel_12988\469282098.py:44: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

**7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/** <br>
You have to find the following details:<br>
A) Name<br>
B) Year span<br>
C) Genre<br>
D) Run time<br>
E) Ratings<br>
F) Votes<br>

In [ ]:
driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()
driver.get("https://www.imdb.com/list/ls095964455/")

C:\Users\HP\AppData\Local\Temp\ipykernel_12596\3986486131.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("chromedriver.exe")

In [ ]:
name=[i.text for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/a")]
year=[i.text for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/span[2]")]
run_time=[i.text for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p/span[3]")]
genre=[i.text for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p/span[5]")]
rating=[i.text for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/div/div/span[2]")]
votes=[i.text for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p[4]/span[2]")]

In [ ]:
df=pd.DataFrame({'Name':name,'Year':year,'Run Time':run_time,'Genre':genre,'Rating':rating,'Votes':votes})
df

,Name,Year,Run Time,Genre,Rating,Votes
0,Game of Thrones,(2011–2019),57 min,"Action, Adventure, Drama",9.2,"2,117,162"
1,Stranger Things,(2016– ),51 min,"Drama, Fantasy, Horror",8.7,"1,206,362"
2,The Walking Dead,(2010–2022),44 min,"Drama, Horror, Thriller",8.1,"1,003,547"
3,13 Reasons Why,(2017–2020),60 min,"Drama, Mystery, Thriller",7.5,"296,457"
4,The 100,(2014–2020),43 min,"Drama, Mystery, Sci-Fi",7.6,"255,380"
...,...,...,...,...,...,...
95,Reign,(2013–2017),42 min,Drama,7.4,"50,655"
96,A Series of Unfortunate Events,(2017–2019),50 min,"Adventure, Comedy, Drama",7.8,"62,518"
97,Criminal Minds,(2005– ),42 min,"Crime, Drama, Mystery",8.1,"202,168"
98,Scream: The TV Series,(2015–2019),45 min,"Comedy, Crime, Drama",7.1,"41,972"
99,The Haunting of Hill House,(2018),572 min,"Drama, Horror, Mystery",8.6,"249,875"

In [ ]:
driver.close()

* Q8. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code

In [ ]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element(By.XPATH,"//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

    #scraping datatypes
data_type=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping task-
default_task=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping attribute type-
attr_type=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping instances-
no_of_instances=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping no of attribute-
no_of_attributes=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)

year-dataset names
year=[]
try:
    info=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,'Data_type':data_type,'Task':default_task,'Attribute_type':attr_type,'No_of_instances':no_of_instances,
'No_of_attributes':no_of_attributes,'Year':year})
df

C:\Users\HP\AppData\Local\Temp\ipykernel_12988\4369422.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome("chromedriver.exe")

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

In [ ]:
driver.close()

**9. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/** <br>
You have to find the following details:<br>
A) Name<br>
B) Designation<br>
C) Company<br>
D) Skills they hire for <br>
E) Location<br>
**Note: - From naukri.com homepage click on the recruiters option and  on the search page type Data science and
click on search. All this should be done through code**

In [ ]:
driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()
driver.get('https://www.naukri.com/hr-recruiters-consultants')

C:\Users\HP\AppData\Local\Temp\ipykernel_12596\1210443555.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("chromedriver.exe")

In [ ]:
#giving input as datascience in search input box
search_Data_science = driver.find_element(By.XPATH,"//input[@class='sugInp']")
search_Data_science.send_keys('Data Science')
#clicking on search button
search_btn = driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button")
search_btn.click()

In [ ]:
name=[]
desig=[]
comp=[]
loc=[]
recruiter=[i.text.split('\n') for i in driver.find_elements(By.XPATH,"//p[@class='highlightable']")]
for i in recruiter:
    try:
        name.append(i[0])
    except:
        name.append('-')
    try:
        desig.append(i[1])
    except:
        desig.append('-')
    try:
        comp.append(i[2])
    except:
        comp.append('-')
    try:
        loc.append(i[3])
    except:
        loc.append('-')
skill=[i.text for i in driver.find_elements(By.XPATH,"//div[@class='hireSec highlightable']")]

In [ ]:
df=pd.DataFrame({'Name':name,'Designation':desig,'Company':comp,'Location':loc,'Skill':skill})
df

,Name,Designation,Company,Location,Skill
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
11,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,Mumbai,"Data Science, Python, Data Analytics"
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
16,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
19,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
25,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,Gurgaon,"Research, Digital Marketing, Analytics, Softwa..."
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
29,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,-,"Signal Processing, Machine Learning, Neural Ne..."
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
32,Avnish Mishra,Senior Technical &amp; Corporate Recruiter,RMS Risk Management Solutions,Noida,"Data Science, Machine Learning, Deep Learning,..."
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
34,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
35,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
36,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
37,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
38,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
43,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
46,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
48,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
49,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."

In [ ]:
driver.close()